version: 3.8

services:
  jenkins:
    restart: always
    build: . 
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /mnt/archive/jenkins:/usr/local/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
