name: Docker Image CI + build + push

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=docker,push=false" \
          --file ./Dockerfile . \
          -t benjaminnomine/rpi-jenkins
    - name: List images
      run: docker images list
    - name: Docker registry login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker push benjaminnomine/rpi-jenkins:latest
